<a href="https://colab.research.google.com/github/prachikushwaha007-ai/Python_for_Data_Science--NPTEL/blob/main/5_NumPy_Array_NPTEL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
list1= [1,2,3,4,5,6]
print(list1)

[1, 2, 3, 4, 5, 6]


In [ ]:
# To make an numpy array from a list.
import numpy as np

In [ ]:
arr = np.array(list1, dtype = int)
print(arr)

[1 2 3 4 5 6]


In [ ]:
print(type(arr))
print(len(arr))
# no. of axis of an array.
print(arr.ndim)
print(arr.shape) # 6 rows, 1 column

<class 'numpy.ndarray'>
6
1
(6,)


In [ ]:
# to reshape an array with row and col.
arr2 = arr.reshape(3,2)
print(arr2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
arr3 = arr.reshape(3,-1)
print(arr3)
 # in large array using -1 to calculate automatically col.

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(arr3.ndim)

2


In [ ]:
## initializing numpy arrays from a nested python list.
list2 = [1,2,3,4,5]
list3 = [2,3,4,5,6]
list4 = [9,7,6,8,9]

arr4 = np.array([list2,list3,list4])
print(arr4)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [ ]:
arr4.tolist()

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [9, 7, 6, 8, 9]]

In [ ]:
print(arr4.shape)

(3, 5)


In [ ]:
arr4.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [ ]:
# Numpy-Attributes_ [[]]
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [ ]:
# reshape the n dim array.
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# to create a sequence of values and then created as an array using range fn.
r = range(24)
print(r)

range(0, 24)


In [ ]:
# to creat a sequence of values, use arange.
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [ ]:
# to reshaping the array 'a'.
b = a.reshape(6,4,1)
print(b)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]
  [ 7]]

 [[ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]]

 [[16]
  [17]
  [18]
  [19]]

 [[20]
  [21]
  [22]
  [23]]]


In [ ]:
# NumPy Arithmetic Operations.
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
print(x+y) # print(np.add(x+y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x-y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(x.dot(y)) # rows(x)*cols(y)

[[19. 22.]
 [43. 50.]]


In [ ]:
# numpy.sum()- returns sum of all array elements over a given axis.
print(np.sum(x))

10.0


In [ ]:
# sum of each column.(axis=0; performing sum op. on col. and axis=1; sum of rows.)
print(np.sum(x, axis=0))

[4. 6.]
